export const FETCH_CARD_COMMENTS = 'FETCH_CARD_COMMENTS';
export const FETCH_CARD_COMMENTS_FAIL = 'FETCH_CARD_COMMENTS_FAIL';
export const FETCH_CARD_COMMENTS_SUCCESS = 'FETCH_CARD_COMMENTS_SUCCESS';
export const ADD_CARD_COMMENTS = 'ADD_CARD_COMMENTS';
export const ADD_CARD_COMMENTS_FAIL = 'ADD_CARD_COMMENTS_FAIL';
